[package]
name = "issue-handler"
version = "0.1.0"
authors = ["Emil Ohlsson <kotte@kottland.net>"]

[dependencies]
git2 = "0.7.1"
reqwest = "0.8.5"
toml = "0.4.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
prettytable-rs = "^0.6"
